<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="pagebuilder-modal-content-body">
    <p><?= /* @escapeNotVerified */
        __('This will change your Admin and storefront by:') ?></p>
    <ul>
        <li>
            <?=
            /* @escapeNotVerified */
            __(
                '<strong>Removing PageBuilder\'s advanced content tools</strong> '
                . 'from their assigned text fields and adding a basic text editor as replacement.'
            )
            ?>
        </li>
        <li>
            <?=
            /* @escapeNotVerified */
            __(
                '<strong>Potentially creating display errors on your storefront</strong>, due to content reformatting. '
                . 'Also, some content may no longer be editable from within the Admin.'
            )
            ?>
        </li>
    </ul>
</div>