<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\PageBuilder\Block\Adminhtml\ContentType\Products\Conditions */
?>
<label class="admin__field-label">
    <span><?= $block->escapeHtml(__('Condition')) ?></span>
</label>
<div class="admin__field-control">
    <div class="rule-tree">
        <fieldset id="<?= $block->escapeHtmlAttr($block->getFormNamespace()) ?>" class="fieldset">
            <div class="rule-tree-wrapper">
                <div data-role="pagebuilder-product-conditions-form-placeholder"></div>
            </div>
        </fieldset>
    </div>
</div>

<script type="text/x-magento-init"><?= /* @noEscape */ $block->getConfigJson() ?></script>