<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Full width row Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Row
 */
if ($block->getBackgroundStyles()) :
    $block->setCssClasses('with-media-background');
endif;
?>
<div class="bluefoot-row <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <?php echo $block->getRenderedChildHtml(); ?>
</div>