<script type="text/x-magento-init">
{ "*": { "Gene_BlueFoot/js/main": {} } }
</script>
<script type="text/javascript">
    // Define a noConflict version of jQuery
    define('cms-config', ['jquery-cms'], function (jQuery) {
        return jQuery.parseJSON('<?php echo $this->getConfig(); ?>');
    });
</script>

<?php
/**
 * Declare the stages mark up
 */
?>
<script id="gene-cms-alert" type="x-tmpl-mustache">
    <div class="gene-cms-modal-background {{class}}">
        <div class="gene-cms-modal" data-model="true">
            <div class="gene-cms-modal-title">{{{title}}} <a href="#" class="gene-cms-close"><i class="fa fa-times"></i></a></div>
            <div class="gene-cms-modal-content">{{{message}}}</div>
            <div class="gene-cms-modal-buttons">
                {{#buttons}}
                <button type="button" class="gene-cms-modal-button {{class}}" data-button="{{code}}">{{label}}</button>
                {{/buttons}}
            </div>
        </div>
    </div>
</script>

<script id="gene-cms-stage-template" type="x-tmpl-mustache">
    <div class="gene-cms-stage gene-cms-stage-{{id}}">
        <div class="gene-cms-stage-panel">
            {{{panel}}}
        </div>
        <div class="gene-cms-stage-content">
            <div class="gene-cms-stage-content-inner">

            </div>
            <button type="button" class="gene-cms-add-row"><i class="fa fa-plus"></i> Add Row</button>
        </div>
    </div>
</script>

<script id="gene-cms-stage-panel-template" type="x-tmpl-mustache">
    <img src="//www.gene.co.uk/wp-content/themes/gene/images/logos/main.png" />
    <div class="gene-cms-stage-panel-content-types">
        <ul class="gene-cms-stage-panel-content-types-ul">
            {{#content-type-groups}}
            <li class="gene-cms-group {{code}}">
                <a href="#" class="gene-cms-group-name">{{{icon}}} {{name}}</a>
                <ul class="gene-cms-stage-panel-group-types gene-cms-stage-panel-group-types-{{code}}">
                {{#types}}
                    <li class="gene-cms-content-type">
                        <a data-type="{{code}}" data-color="{{color}}" data-colortheme="{{color_theme}}" href="#" class="gene-cms-draggable gene-cms-theme-{{color_theme}}">
                            <span class="gene-cms-content-type-icon" style="background: {{color}};">{{{icon}}}</span>
                            <span class="gene-cms-content-type-name">{{name}}</span>
                        </a>
                    </li>
                {{/types}}
                </ul>
            </li>
            {{/content-type-groups}}
        </ul>
    </div>
</script>

<script id="gene-cms-stage-configure-template" type="x-tmpl-mustache">
    <div class="gene-cms-configure-sidebar">
        <div class="gene-cms-configure-sidebar-overlay"></div>
        <div class="gene-cms-configure-sidebar-container">
            <h2>
                <span class="color: {{color}};">{{{icon}}}</span> {{ name }}
                <a href="#" class="gene-cms-configure-close gene-cms-close-configure"><i class="fa fa-times"></i></a>
            </h2>
            <form action="" id="gene-cms-configure-form" class="gene-cms-configure-form">
                {{#groups}}
                    <div class="gene-cms-configure-group {{class}}">
                        <h3>{{ name }}</h3>
                        <ul class="gene-cms-configure-group-fields">
                            {{#fields}}
                            <li class="gene-cms-configure-group-field gene-cms-{{code}}" data-field="{{code}}">

                            </li>
                            {{/fields}}
                        </ul>
                    </div>
                {{/groups}}
                <div class="gene-cms-configure-buttons">
                    <button type="button" class="gene-cms-button gene-cms-configure-cancel gene-cms-button-skinny gene-cms-button-red gene-cms-close-configure">Cancel</button>
                    <button type="submit" class="gene-cms-button gene-cms-configure-save gene-cms-button-skinny gene-cms-button-green">Save</button>
                </div>
            </form>
        </div>
    </div>
</script>

<script id="gene-cms-row-template" type="x-tmpl-mustache">
    <div class="gene-cms-row">
        <div class="gene-cms-column-selection">
            <ul class="gene-cms-columns">
            {{#columns}}
                <li class="gene-cms-column-option gene-cms-column-{{number}}"></li>
            {{/columns}}
            </ul>
        </div>
        <div class="gene-cms-row-content gene-cms-droppable">
            <div class="empty-text">
                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 612 641" enable-background="new 0 0 612 641" xml:space="preserve">
                    <g>
                        <g>
                            <path d="M396.5,624H242.2c-7,0-12.8-5.7-12.8-12.8c0-35.1,28.6-63.8,63.8-63.8h20.2L216,450c-7.5-7.5-11.7-17.5-11.7-28.2
                                s4.2-20.6,11.7-28.2c15-15,41.2-15,56.3,0l22.8,22.8c1.9-4.4,4.7-8.4,8.2-12c8.8-8.8,21.5-13,33.7-11.3
                                c1.5-7.5,5.1-14.8,10.9-20.6c11.1-11.1,27.3-14.3,41.2-9.4c1.9-5.9,5.1-11.4,9.8-16.1c15.5-15.5,40.8-15.5,56.3,0l39.5,39.5
                                c26.3,26.3,40.7,61.2,40.7,98.3C535.5,561.6,473.2,624,396.5,624z M257.2,598.5h139.4c62.6,0,113.5-50.9,113.5-113.5
                                c0-30.3-11.8-58.8-33.2-80.2l-39.5-39.5c-5.6-5.6-14.6-5.6-20.2,0c-5.6,5.6-5.6,14.6,0,20.2c2.5,2.5,3.7,5.8,3.7,9s-1.2,6.5-3.7,9
                                c-5,5-13.1,5-18,0l-12.8-12.8c-5.6-5.6-14.6-5.6-20.2,0c-2.7,2.7-4.2,6.3-4.2,10.1s1.5,7.4,4.2,10.1l12.8,12.8
                                c2.5,2.5,3.7,5.7,3.7,9s-1.2,6.5-3.7,9c-5,5-13.1,5-18,0l-19.1-19.1c-5.4-5.4-14.8-5.4-20.2,0c-2.7,2.7-4.2,6.3-4.2,10.1
                                c0,3.8,1.5,7.4,4.2,10.1l31.9,31.9c2.5,2.5,3.7,5.8,3.7,9s-1.2,6.5-3.7,9c-5,5-13.1,5-18,0l-81-81c-5.4-5.4-14.8-5.4-20.2,0
                                c-2.7,2.7-4.2,6.3-4.2,10.1c0,3.8,1.5,7.4,4.2,10.1l119.2,119.2c3.6,3.6,4.7,9.1,2.8,13.9c-2,4.8-6.6,7.9-11.8,7.9h-51
                                C276.6,573,262.4,583.6,257.2,598.5z"/>
                        </g>
                        <g>
                            <path d="M89.2,534.7C40,534.7,0,494.7,0,445.5s40-89.2,89.2-89.2s89.2,40,89.2,89.2S138.5,534.7,89.2,534.7z M89.2,381.7
                                c-35.1,0-63.8,28.6-63.8,63.7s28.6,63.8,63.8,63.8s63.8-28.6,63.8-63.7S124.4,381.7,89.2,381.7z"/>
                        </g>
                        <g>
                            <path d="M540.8,188.3c-5.7,0-11-3.9-12.4-9.7c-1.7-6.9,2.5-13.7,9.4-15.4c6.9-1.7,13.5-4.5,19.4-8.3c5.9-3.8,13.8-2.1,17.6,3.8
                                c3.8,5.9,2.1,13.8-3.8,17.6c-8.4,5.4-17.5,9.3-27.2,11.7C542.8,188.2,541.8,188.3,540.8,188.3z M490.9,183.6
                                c-1.8,0-3.6-0.4-5.3-1.1c-9-4.1-17.3-9.7-24.5-16.6c-5.1-4.8-5.3-12.9-0.4-18c4.9-5.1,13-5.3,18-0.4c5.2,4.9,11,8.9,17.5,11.9
                                c6.4,2.9,9.2,10.5,6.3,16.9C500.4,180.8,495.8,183.6,490.9,183.6z M595.1,139c-1.4,0-2.8-0.2-4.2-0.7c-6.7-2.3-10.2-9.6-7.9-16.2
                                c2.3-6.7,3.5-13.7,3.5-20.9c0-6.1-0.8-12.2-2.5-18c-2-6.8,1.9-13.8,8.6-15.8c6.8-1.9,13.8,1.9,15.8,8.6c2.4,8.2,3.6,16.6,3.6,25.2
                                c0,10-1.6,19.8-4.9,29.2C605.3,135.7,600.3,139,595.1,139z M447,124.8c-6.2,0-11.7-4.6-12.6-10.9c-0.6-4.2-0.9-8.4-0.9-12.7
                                c0-5.8,0.5-11.4,1.6-16.9c1.3-6.9,8-11.4,14.9-10.1c6.9,1.3,11.4,8,10.1,14.9c-0.7,3.9-1.1,8-1.1,12.1c0,3.1,0.2,6.1,0.6,9.1
                                c1,7-3.8,13.4-10.8,14.4C448.2,124.8,447.6,124.8,447,124.8z M472.7,56.1c-3.6,0-7.1-1.5-9.6-4.4c-4.6-5.3-4-13.4,1.3-18
                                c7.5-6.5,16-11.7,25.2-15.4c6.5-2.6,13.9,0.6,16.6,7.1c2.6,6.5-0.5,14-7.1,16.6c-6.6,2.7-12.7,6.4-18.1,11
                                C478.6,55.1,475.6,56.1,472.7,56.1z M567.1,51.6c-2.6,0-5.2-0.8-7.4-2.4c-5.8-4.1-12.2-7.2-19-9.2c-6.8-2-10.6-9.1-8.6-15.8
                                c2-6.8,9.1-10.6,15.8-8.6c9.6,2.8,18.5,7.2,26.6,13c5.7,4.1,7.1,12.1,3,17.8C575,49.8,571.1,51.6,567.1,51.6z"/>
                        </g>
                        <g>
                            <path d="M127.5,381.7c-1,0-2-0.1-3-0.4c-6.9-1.6-11.1-8.5-9.4-15.4c2-8.2,5.5-17.2,10.4-26.6c3.3-6.2,11-8.7,17.2-5.4
                                c6.2,3.3,8.6,11,5.4,17.2c-4,7.5-6.7,14.5-8.2,20.7C138.5,377.8,133.3,381.7,127.5,381.7z M165.6,316c-2.8,0-5.7-0.9-8.1-2.9
                                c-5.5-4.5-6.2-12.5-1.8-18c5.4-6.5,11.1-13.2,17.3-19.8c4.8-5.2,12.8-5.5,18-0.7c5.2,4.8,5.5,12.9,0.7,18
                                c-5.8,6.3-11.2,12.5-16.3,18.7C172.9,314.4,169.3,316,165.6,316z M218.6,260.7c-3.4,0-6.9-1.4-9.4-4.1c-4.8-5.2-4.4-13.3,0.8-18
                                c6.3-5.8,12.8-11.6,19.4-17.2c5.4-4.5,13.4-4,18,1.4c4.6,5.3,4,13.4-1.4,18c-6.4,5.5-12.7,11.1-18.7,16.7
                                C224.8,259.7,221.7,260.7,218.6,260.7z M277.5,211.8c-3.9,0-7.7-1.7-10.2-5.1c-4.3-5.6-3.1-13.6,2.5-17.8
                                c6.9-5.3,13.9-10.4,20.9-15.3c5.8-4.1,13.7-2.7,17.8,3.1c4.1,5.7,2.7,13.7-3.1,17.8c-6.8,4.8-13.6,9.7-20.3,14.8
                                C282.9,210.9,280.2,211.8,277.5,211.8z M340.8,168.7c-4.3,0-8.5-2.2-10.9-6.1c-3.6-6-1.7-13.8,4.3-17.5c7.7-4.7,15.2-9,22.7-13
                                c6.2-3.4,13.9-1,17.3,5.1c3.4,6.2,1.1,13.9-5.1,17.3c-7.1,3.8-14.3,8-21.6,12.4C345.3,168.1,343.1,168.7,340.8,168.7z
                                 M409.3,134.6c-5.2,0-10.1-3.2-12-8.4c-2.4-6.6,1.1-13.9,7.7-16.3c9.7-3.5,18.7-5.9,26.7-7.3c6.9-1.1,13.5,3.5,14.7,10.5
                                c1.2,6.9-3.5,13.5-10.5,14.7c-6.5,1.1-14.1,3.2-22.4,6.2C412.2,134.4,410.7,134.6,409.3,134.6z"/>
                        </g>
                    </g>
                </svg>

                <h3>Drag content types here, or add columns</h3>
            </div>
        </div>
    </div>
</script>

<script id="gene-cms-option-template" type="x-tmpl-mustache">
    <div class="gene-cms-options" style="background: {{color}};">
        <div class="gene-cms-options-wrapper">
            <ul class="gene-cms-options-links">
                {{#options}}
                    <li class="gene-cms-options-link-{{code}} {{liClass}}" data-code="{{code}}">
                        <a href="#" class="{{classes}}" style="{{{styles}}}" title="{{label}}">{{{icon}}}</a>
                    </li>
                {{/options}}
            </ul>
        </div>
    </div>
</script>

<script id="gene-cms-column-template" type="x-tmpl-mustache">
    {{#columns}}
        <div class="gene-cms-column gene-cms-column-width-{{width}}{{class}} gene-cms-sortable" data-width="{{width}}" style="width: {{cssWidth}}%;">
            <div class="gene-cms-column-content gene-cms-droppable"></div>
            <div class="gene-cms-column-handle"></div>
            <div class="gene-cms-column-resize"></div>
            <div class="gene-cms-column-ghost"></div>
        </div>
    {{/columns}}
</script>

<script id="gene-cms-entity" type="x-tmpl-mustache">
    <div data-type="{{code}}" data-color="{{color}}" href="#" style="border-color: {{color}};{{style}}" class="gene-cms-entity gene-cms-sortable gene-cms-theme-{{color_theme}}">
        <span class="gene-cms-content-type-icon">{{{icon}}}</span>
        <span class="gene-cms-content-type-name">{{name}}</span>
    </div>
</script>

<script id="gene-cms-entity-preview" type="x-tmpl-mustache">
    <div data-type="{{code}}" data-color="{{color}}" href="#" style="border-color: {{color}};{{style}}" class="gene-cms-entity gene-cms-entity-preview gene-cms-sortable gene-cms-theme-{{color_theme}}">
        {{{preview}}}
    </div>
</script>