<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Twitter Feed Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $block->getEntity();
$_size = strtolower($block->getAttributeText('pin_size'));

if ($_entity->getPinBoardId()) : ?>
    <script async defer src="//assets.pinterest.com/js/pinit.js"></script>

    <a data-pin-do="embedBoard" data-pin-board-width="130" data-pin-scale-height="659" data-pin-scale-width="115"
       href="https://www.pinterest.com/MakeupUtopia/inspiring-hair/"></a>
<?php endif; ?>