<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Product List Block Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Catalog_Single
 *
 */
?>
<div class="gene-bluefoot-product-list gene-bluefoot-pagebuilder-block clearfix bluefoot-nomralise-heights-need-init bluefoot-entity-align-{{ align }}">

    {{#category_id.products}}
        <div class="gene-bluefoot-product">
            <img src="{{ image }}" class="gene-bluefoot-product-image"/>
            <div class="gene-bluefoot-product-content bluefoot-normalise-heights">
                <h3 class="gene-bluefoot-product-name">{{ name }}</h3>
                <p class="gene-bluefoot-product-sku">{{ sku }}</p>
                <p class="gene-bluefoot-product-price">{{ price }}</p>
            </div>

        </div>
    {{/category_id.products}}
</div>

<script type="text/javascript">
    var elem = jQuery('.bluefoot-nomralise-heights-need-init');
    if (typeof elem.bluefootNormaliseHeights === 'function') {
        elem.bluefootNormaliseHeights();
        elem.removeClass('bluefoot-nomralise-heights-need-init');
    }
</script>