<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Product List Block Template
 * @var $this Gene_Cms_Block_Entity_Pagebuilder_Block_Catalog_Single
 *
 */
?>
<div class="gene-cms-product-list">

    {{#category_id}}
        <div class="gene-cms-product">
            <img src="{{ image }}" class="gene-cms-product-image"/>
            <h3 class="gene-cms-product-name">{{ name }}</h3>
            <p class="gene-cms-product-sku">{{ sku }}</p>
            <p class="gene-cms-product-price">{{ price }}</p>
        </div>
    {{/category_id}}
</div>