<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Single Product Block Template
 * @var $this Gene_Cms_Block_Entity_Pagebuilder_Block_Catalog_Single
 *
 */
?>
<div class="gene-cms-product">
    <img src="{{ product_id.image }}" class="gene-cms-product-image"/>
    <h3 class="gene-cms-product-name">{{ product_id.name }}</h3>
    <p class="gene-cms-product-sku">{{ product_id.sku }}</p>
    <p class="gene-cms-product-price">{{ product_id.price }}</p>
</div>