<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $uniqueIdentifier = uniqid(); ?>

<div class="block block-subscribe bluefoot-full-width bluefoot-newsletter <?php echo $block->escapeHtmlAttr($block->getClass()); ?>" style="<?php echo $block->escapeHtmlAttr($block->getStyle()); ?>">
    <div class="block-title">
        <strong><span><?php echo $block->escapeHtml($block->getTitle()); ?></span></strong>
    </div>
    <form class="form subscribe" novalidate="novalidate" action="<?php /* @noEscape */ echo $block->getFormActionUrl() ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter-<?php /* @noEscape */ echo $uniqueIdentifier ?>"><?php echo $block->escapeHtml($block->getLabelText()); ?></label>
            </div>
            <div class="input-container">
                <div class="input-box">
                    <input name="email" type="email" id="newsletter-<?php /* @noEscape */ echo $uniqueIdentifier ?>" placeholder="<?php echo $block->escapeHtml($block->getPlaceholder()) ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
                <div class="actions">
                    <button type="submit" title="<?php echo $block->escapeHtml($block->getButtonText()) ?>" class="button">
                        <span><span><?php echo $block->escapeHtml($block->getButtonText()) ?></span></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
