<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Tabs Block Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
?>
<?php if ($block->hasChildEntities('tabs_items')) : ?>
    <?php $_collection = $block->getChildEntities('tabs_items'); ?>
    <div id="bluefoot-tabs-<?php echo $_entity->getId(); ?>"
         class="bluefoot-tabs bluefoot-full-width <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <ul class="bluefoot-tabs-navigation bluefoot-mobile-hidden bluefoot-full-width">
            <?php $_i = 0;
            foreach ($_collection as $_block) :
                $_i++; ?>
                <li>
                    <span
                        class="bluefoot-tab<?php echo ($_i == 1) ? ' active' : ''; ?><?php echo ($_i == count($_collection)) ? ' last' : ''; ?>"
                        data-tab="#bluefoot-tab-<?php echo $_block->getEntity()->getId(); ?>">
                        <?php echo $_block->getEntity()->getTitle(); ?>
                    </span>
                </li>
            <?php
            endforeach;
            ?>
        </ul>

        <div class="bluefoot-tabs-outer bluefoot-full-width">
            <?php $_j = 0;
            foreach ($_collection as $_block) :
                $_j++; ?>
                <?php echo $_block->setCount($_j)->toHtml(); ?>
            <?php
            endforeach;
            ?>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'bluefoot/tabs', 'bluefoot/accordion'], function (jQuery) {
            jQuery('#bluefoot-tabs-<?php echo $_entity->getId(); ?>').bluefootTabs();
            jQuery('#bluefoot-tabs-<?php echo $_entity->getId(); ?>').bluefootAccordion();
        });
    </script>
<?php endif; ?>