<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Anchor Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
?>
<span id="<?php echo $_entity->getAnchorId(); ?>"
      class="bluefoot-anchor <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>></span>