<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Horizontal Rule Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_styles = '';

if ($_entity->getHrWidth()):
    $_styles .= 'width:' . $_entity->getHrWidth() . ';';
endif;
if ($_entity->getHrHeight()):
    $_styles .= 'border-width:' . $_entity->getHrHeight() . ';';
endif;
if ($_entity->getColor()):
    $_styles .= 'border-color:#' . $_entity->getColor() . ';';
endif;

$block->setStyles($_styles);
?>
<hr class="bluefoot-hr <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?> />