<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Newsletter Signup Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 * @var $catalogSearchHelper Magento\Search\Helper\Data
 *
 */
$_entity = $this->getEntity();
$catalogSearchHelper = $this->helper('Magento\Search\Helper\Data');;
?>
<form id="search_mini_form_<?php echo $_entity->getEntityId(); ?>" class="bluefoot-search-form bluefoot-full-width <?php echo $this->getCssAttributes(); ?>" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get"<?php echo $this->getStyleAttributes(); ?>>
    <div class="form-search">
        <label for="search_<?php echo $_entity->getEntityId(); ?>"><?php echo __('Search:') ?></label>
        <input id="search_<?php echo $_entity->getEntityId(); ?>" type="search" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $_entity->getPlaceholder(); ?>"/>
        <button type="submit" title="<?php echo __('Search') ?>" class="button search-button"></button>
        <div id="search_autocomplete_<?php echo $_entity->getEntityId(); ?>" class="search-autocomplete"></div>
    </div>
</form>