<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Tabs Item Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
?>
<div id="bluefoot-tab-<?php echo $_entity->getId(); ?>"
     class="bluefoot-tab-item bluefoot-tab-content bluefoot-full-width<?php echo ($block->getCount() == 1) ? ' active' : ''; ?> <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <div class="bluefoot-accordion-outer bluefoot-full-width">
        <h4 class="bluefoot-accordion-link bluefoot-full-width bluefoot-mobile-only"><?php echo $_entity->getTitle(); ?></h4>

        <div class="bluefoot-accordion-inner bluefoot-full-width bluefoot-tab-inner">
            <?php echo $_entity->getTextarea(); ?>
        </div>
    </div>
</div>