<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Wrapper for product sections to include title
 *
 * @var \Magento\Framework\View\Element\Template $block
 */
$childHtml = $block->getChildHtml();
?>
<?php if (trim($childHtml) !== "") : ?>
    <div class="product-full-width-section">
        <h2 class="product-section-title"><?= $block->escapeHtml($block->getTitle()); ?></h2>
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>