<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product additional attributes template
 *
 * @var $block \Magento\PageBuilder\Block\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $helper = $this->helper('Magento\Catalog\Helper\Output');
    $product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="pagebuilder-attributes-wrapper">
        <?php foreach ($_additional as $_data): ?>
            <div class="page-main">
                <h2 class="product-section-title"><?= $block->escapeHtml(__($_data['label'])) ?></h2>
            </div>
            <div class="pagebuilder-attribute-wrapper">
                <?= /* @escapeNotVerified */ $helper->productAttribute($product, $_data['value'], $_data['code']) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif;?>
