<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php $components = $block->getComponents(); if ($components): ?>
    <script type="text/javascript">
        require(['underscore', 'uiRegistry'], function (_, registry) {
            _.each(<?php /* noEscape */ echo json_encode($components) ?>, function (component, key) {
                registry.set('component_' + key, component);
            });
        });
    </script>
<?php endif; ?>