<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Advanced Slider Item Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>

<div class="bluefoot-advanced-slider-item bluefoot-entity-align-{{ align }}" style="background: url('/pub/media/gene-cms/{{ background_image }}');background-size:cover;background-position:center center;">
    <div class="bluefoot-advanced-slider-content">
        <h3>{{ title }}</h3>
        {{#textarea}}
        <div class="bluefoot-advanced-slider-text">
            {{{ textarea }}}
        </div>
        {{/textarea}}

        {{#link_text}}
        <!-- if link text exists Do this -->
        <button class="gene-bluefoot-block-button">{{ link_text }}</button>
        {{/link_text}}

    </div>
</div>
