<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Driver Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>
<div class="gene-bluefoot-driver gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <img src="/pub/media/gene-cms{{ image }}" />
    <span class="gene-bluefoot-driver-title">{{ link_text }}</span>
</div>