<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Facebook Feed Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
?>
<div class="gene-bluefoot-static-block gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">

    <div id="fb-root"></div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="fb-page" data-href="{{ facebook_url }}" data-tabs="{{ facebook_tabs }}" data-width="{{ facebook_width }}" data-height="{{ facebook_height }}" data-adapt-container-width="true" data-show-facepile="true">

        <div class="fb-xfbml-parse-ignore">
            <blockquote cite="{{ facebook_url }}">
                <a href="{{ facebook_url }}">{{ facebook_page }}</a>
            </blockquote>
        </div>
    </div>

</div>