<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
// @codingStandardsIgnoreFile
$uniqueIdentifier = uniqid();
?>

<div class="<?= $block->escapeHtmlAttr($block->getClasses()); ?>" style="<?= $block->escapeHtmlAttr($block->getStyles()); ?>">
    <div class="block newsletter">
        <div class="title"><strong><?= $block->escapeHtml($block->getTitle() ?? __('Newsletter')) ?></strong></div>
        <div class="content">
            <form class="form subscribe"
                  novalidate
                  action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'>
                <div class="field newsletter">
                    <label class="label" for="newsletter-<?= /* @noEscape */ $uniqueIdentifier ?>"><span><?= $block->escapeHtml($block->getLabelText() ?? __('Sign Up for Our Newsletter:')) ?></span></label>
                    <div class="control">
                        <input name="email" type="email" id="newsletter-<?= /* @noEscape */ $uniqueIdentifier ?>"
                               placeholder="<?= $block->escapeHtml($block->getPlaceholder() ?? __('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"/>
                    </div>
                </div>
                <div class="actions">
                    <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr($block->getButtonText() ?? __('Subscribe')) ?>" type="submit">
                        <span><?= $block->escapeHtml($block->getButtonText() ?? __('Subscribe')) ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>