<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
// @codingStandardsIgnoreFile

$uniqueIdentifier = uniqid();
?>

<div data-role="newsletter" class="block block-subscribe pagebuilder-full-width pagebuilder-newsletter <?= $block->escapeHtmlAttr($block->getClass()); ?>" style="<?= $block->escapeHtmlAttr($block->getStyle()); ?>">
    <div class="block-title">
        <strong><span><?= $block->escapeHtml($block->getTitle()); ?></span></strong>
    </div>
    <form class="form subscribe" novalidate="novalidate" action="<?= /* @noEscape */ $block->getFormActionUrl() ?>" method="post" data-mage-init='{"validation": {"errorClass": "mage-error"}}' id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter-<?= /* @noEscape */ $uniqueIdentifier ?>"><?= $block->escapeHtml($block->getLabelText()); ?></label>
            </div>
            <div class="input-container">
                <div class="input-box">
                    <input name="email" type="email" id="newsletter-<?= /* @noEscape */ $uniqueIdentifier ?>" placeholder="<?= $block->escapeHtml($block->getPlaceholder()) ?>" data-validate="{required:true, 'validate-email':true}"/>
                </div>
                <div class="actions">
                    <button type="submit" title="<?= $block->escapeHtml($block->getButtonText()) ?>" class="button">
                        <span><span><?= $block->escapeHtml($block->getButtonText()) ?></span></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
