<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Carousel Slider Item Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $block->getEntity();
$_count = $block->getCount();
$_urlPrefix = $block->getMediaUrl() . 'gene-cms';
$block->setStyles('background-image: url(' . $_urlPrefix . $_entity->getBackgroundImage() . ');');
$_classes = 'slide-' . $_count;
// Hide all but the first slide
if ($_count > 1) :
    $_classes .= ' hidden-on-load';
endif;
// If there is a link but no button make the whole slide link
$_noButtonLink = '';
if (!$_entity->getLinkText() && $_entity->getLinkUrl()) :
    $_classes .= ' bluefoot-slide-with-link';
    $_noButtonLink = 'onclick="location.href=\'' . $_entity->getLinkUrl() . '\'"';
endif;
$_color = $_entity->getTextColor();
$block->setCssClasses($_classes);
?>
<div
    class="bluefoot-advanced-slide <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?><?php echo $_noButtonLink; ?>>
    <div class="bluefoot-wrapper">
        <div
            class="bluefoot-advanced-slide-content<?php echo ($_entity->getHasOverlay()) ? ' bluefoot-with-overlay' : ''; ?>">
            <div class="bluefoot-full-width">
                <?php if ($_entity->getTitle()) : ?>
                    <h3<?php echo ($_color) ? ' style="color:#' . $_color . ';"' : ''; ?>><?php echo $_entity->getTitle(); ?></h3>
                <?php endif; ?>
                <?php if ($_entity->getTextarea()) : ?>
                    <div class="bluefoot-advanced-slide-text bluefoot-full-width">
                        <?php echo $_entity->getTextarea(); ?>
                    </div>
                <?php endif; ?>
                <?php if ($_entity->getLinkText() && $_entity->getLinkUrl()) : ?>
                    <button type="button" onclick="location.href='<?php echo $_entity->getLinkUrl(); ?>'"
                            class="button">
                        <span><span><?php echo $_entity->getLinkText(); ?></span></span>
                    </button>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>