<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Driver Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $block->getEntity();
$_urlPrefix = $block->getMediaUrl() . 'gene-cms';
?>
<div id="bluefoot-driver-<?php echo $_entity->getId(); ?>"
     class="bluefoot-driver <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <a href="<?php echo $_entity->getLinkUrl(); ?>"<?php echo ($_entity->getTargetBlank()) ? ' target="_blank"' : ''; ?>>
        <?php if ($_entity->getMobileImage()) : ?>
            <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>" alt="<?php echo $_entity->getAltTag(); ?>"
                 title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
            <img src="<?php echo $_urlPrefix . $_entity->getMobileImage(); ?>"
                 alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>"
                 class="bluefoot-mobile-only"/>
        <?php else : ?>
            <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>" alt="<?php echo $_entity->getAltTag(); ?>"
                 title="<?php echo $_entity->getTitleTag(); ?>"/>
        <?php endif; ?>
        <?php if ($_text = $_entity->getLinkText()) : ?>
            <span class="bluefoot-driver-text">
            <span><?php echo $_text; ?></span>
        </span>
        <?php endif; ?>
    </a>
</div>