<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Image Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_urlPrefix = $block->getMediaUrl() . 'gene-cms';
?>
    <figure id="bluefoot-image-<?php echo $_entity->getId(); ?>"
            class="bluefoot-image <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <?php if ($_entity->getHasLightbox()) : ?>
        <a href="<?php echo $block->getImageUrl($_entity->getImage()); ?>" class="bluefoot-lightbox"
           title="<?php echo $_entity->getTitleTag(); ?>">
            <?php endif; ?>
            <?php if ($_entity->getMobileImage()) : ?>
                <img src="<?php echo $block->getImageUrl($_entity->getImage()); ?>" alt="<?php echo $_entity->getAltTag(); ?>"
                     title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
                <img src="<?php echo $block->getImageUrl($_entity->getMobileImage()); ?>"
                     alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>"
                     class="bluefoot-mobile-only"/>
            <?php else : ?>
                <img src="<?php echo $block->getImageUrl($_entity->getImage()); ?>" alt="<?php echo $_entity->getAltTag(); ?>"
                     title="<?php echo $_entity->getTitleTag(); ?>"/>
            <?php endif; ?>
            <?php if ($_entity->getHasLightbox()) : ?>
        </a>
    <?php endif; ?>
        <?php if ($_entity->getShowCaption() && $_entity->getTitleTag()) : ?>
            <figcaption>
                <?php echo $_entity->getTitleTag(); ?>
            </figcaption>
        <?php endif; ?>
    </figure>

<?php if ($_entity->getHasLightbox()) : ?>
    <script type="text/javascript">
        requirejs(['jquery', 'fancybox'], function (jQuery) {
            jQuery('#bluefoot-image-<?php echo $_entity->getId(); ?> .bluefoot-lightbox').fancybox();
        });
    </script>
<?php endif; ?>