<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Carousel Template - this carousel uses the jQuery plugin Slick <http://kenwheeler.github.io/slick/>
 * Thanks to Ken Wheeler for allowing us to distribute his plugin with the Gene CMS
 *
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $block->getEntity();

if ($_entity->getShowDots()) :
    $block->setCssClasses('bluefoot-slider-with-dots');
endif;

?>
<?php if ($block->hasChildEntities('slider_items')) : ?>
    <?php $_collection = $block->getChildEntities('slider_items'); ?>
    <div id="bluefoot-slider-<?php echo $block->getEntity()->getId(); ?>"
         class="bluefoot-slider bluefoot-full-width <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <?php $_i = 0;
        foreach ($_collection as $_block) :
            $_i++; ?>
            <?php echo $_block->setCount($_i)->toHtml(); ?>
        <?php
        endforeach;
        ?>
    </div>

    <script type="text/javascript">
        require(['jquery', 'slick'], function (jQuery) {
            jQuery(function () {
                /* [Slick JS] */
                jQuery('#bluefoot-slider-<?php echo $block->getEntity()->getId(); ?>').slick({
                    infinite: <?php echo ($_entity->getIsInfinite()) ? 'true' : 'false' ; ?>,
                    lazyLoad: 'ondemand',
                    dots: <?php echo ($_entity->getShowDots()) ? 'true' : 'false' ; ?>,
                    slidesToShow: <?php echo ($_entity->getSlidesToShow()) ? $_entity->getSlidesToShow() : 1 ; ?>,
                    slidesToScroll: <?php echo ($_entity->getSlidesToScroll()) ? $_entity->getSlidesToScroll() : 1 ; ?>,
                    arrows: <?php echo ($_entity->getShowArrows()) ? 'true' : 'false' ; ?>,
                    autoplay: <?php echo ($_entity->getAutoplay()) ? 'true' : 'false' ; ?>,
                    autoplaySpeed: <?php echo ($_entity->getAutoplayPlaySpeed()) ? $_entity->getAutoplayPlaySpeed() : '5000' ; ?>,
                    fade: <?php echo ($_entity->getFade()) ? 'true' : 'false' ; ?>,
                    prevArrow: '<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
                    nextArrow: '<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
                    <?php echo ($_entity->getSliderAdditionalSettings()) ? ',' . $_entity->getSliderAdditionalSettings()  : '' ; ?>
                });
            });
            jQuery('#bluefoot-slider-<?php echo $block->getEntity()->getId(); ?>').on('init', function (event, slick) {
                slick.$slider.addClass('slick-visible');
            });
        });
    </script>

<?php endif; ?>