<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Map Block Template
 * @var $block @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\Video
 *
 */
$_entity = $block->getEntity();
$_video = $block->getVideoData();
$_styles = '';
if ($_entity->getVideoHeight()) :
    $_styles .= 'height:' . $_entity->getVideoHeight() . ';';
endif;
if ($_entity->getVideoWidth()) :
    $_styles .= 'width:' . $_entity->getVideoWidth() . ';';
endif;

if ($_video) : ?>
    <div id="bluefoot-video-<?php echo $_entity->getEntityId(); ?>"
         class="bluefoot-video  <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <iframe
            src="<?php echo $_video->getUrl() ?>"<?php echo ($_entity->getVideoHeight()) ? ' height="' . $_entity->getVideoHeight() . '"' : ''; ?><?php echo ($_entity->getVideoWidth()) ? ' width="' . $_entity->getVideoWidth() . '"' : ''; ?>
            style="<?php echo $_styles; ?>" frameborder="0"></iframe>
    </div>
<?php endif; ?>