<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Accordion Item Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>
<div class="bluefoot-accordion-outer gene-bluefoot-accordion-item bluefoot-entity-align-{{ align }}">
    <h4 class="bluefoot-accordion-link gene-bluefoot-accordion-item-heading no-edit">{{title}}</h4>
    <div class="bluefoot-accordion-inner gene-bluefoot-accordion-item-content" style="display: none;">
        {{{textarea}}}
    </div>
</div>