<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Accordion Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>
<div class="bluefoot-accordion bluefoot-accordion-need-init gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    {{#child_blocks.accordion_items}}
        {{{html}}}
    {{/child_blocks.accordion_items}}
</div>

<script type="text/javascript">
    var elem = jQuery('.bluefoot-accordion-need-init');
    elem.bluefootAccordion();
    elem.find('.bluefoot-accordion-outer').first().addClass('active');
    elem.find('.bluefoot-accordion-inner').first().css('display', '');
    elem.removeClass('bluefoot-accordion-need-init');
</script>