<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Code Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
?>
<div class="gene-bluefoot-code gene-bluefoot-code-need-init gene-bluefoot-pagebuilder-block clearfix">
    <pre><code>{{ html }}</code></pre>
</div>
<script type="text/javascript">
    var elem = jQuery('.gene-bluefoot-code-need-init');
    elem.find('code').each(function(i, block) {
        hljs.highlightBlock(block);
    });
    elem.removeClass('gene-bluefoot-code-need-init');
</script>