<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Newsletter Signup Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>
<div class="gene-bluefoot-search-block gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <span class="gene-bluefoot-search-block-input">
        {{{ placeholder }}}
        <button type="button" class="gene-bluefoot-block-button"><i class="fa fa-search"></i></button>
    </span>
</div>