<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Tabs Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
?>
<div class="gene-bluefoot-tabs gene-bluefoot-tabs-need-init gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <div class="gene-bluefoot-tabs-navigation">
        {{#child_blocks.tabs_items}}
            {{{html}}}
        {{/child_blocks.tabs_items}}
    </div>
    <div class="gene-bluefoot-tabs-content">
        {{#child_blocks.tabs_items}}
            {{{html}}}
        {{/child_blocks.tabs_items}}
    </div>
</div>

<script type="text/javascript">
    var elem = jQuery('.gene-bluefoot-tabs-need-init');
    // Used as an attempt to avoid ID clashing
    var uniqueId = Math.random().toString(36).substring(7);
    // Remove unwanted content, @todo - don't load it in the first place
    elem.find('.gene-bluefoot-tabs-content .bluefoot-tab').remove();
    elem.find('.gene-bluefoot-tabs-navigation .bluefoot-tab-content').remove();

    // Add Data attributes + IDs used for the tabs
    elem.find('.bluefoot-tab').each(function(i){
        jQuery(this).attr('data-tab', '#tab-' + (i+1) + '-' + uniqueId);
    });
    elem.find('.bluefoot-tab-content').each(function(i){
        jQuery(this).attr('id', 'tab-' + (i+1) + '-' + uniqueId);
    });
    elem.bluefootTabs();
    elem.find('.bluefoot-tab').first().addClass('active');
    elem.find('.bluefoot-tab-content').first().addClass('active');
    elem.removeClass('gene-bluefoot-tabs-need-init');
</script>