<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_product = $block->getProduct();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

/* @var \Magento\PageBuilder\Block\ContentType\Product $block */
?>

<?php if ($_product) : ?>
    <?php
    if (strtolower($block->getViewMode()) == 'grid') {
        $viewMode = 'grid';
        $image = 'pagebuilder_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'pagebuilder_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="page-products pagebuilder-product-single <?= $block->escapeHtmlAttr($block->getClass()); ?>" style="<?= $block->escapeHtmlAttr($block->getStyle()); ?>">
        <div class="products <?= /* @noEscape */ $viewMode; ?> products-<?= /* @noEscape */ $viewMode; ?>">
            <?php $iterator = 1; ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <li class="item product product-item">
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml(); ?>
                        </a>

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */
                                   echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product); ?>

                            <div class="product-item-inner">
                                <div
                                    class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div
                                        class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()) : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo \Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][\Magento\Framework\App\ActionInterface::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?= $block->getBlockHtml('formkey') ?>

                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else : ?>
                                            <?php if ($_product->getIsSalable()) : ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                        echo __('In stock') ?></span></div>
                                            <?php else : ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?= $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */
                                               echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */
                                                    echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?= $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */
                                           echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php /* @escapeNotVerified */
                                                echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
                                <?php if ($showDescription) : ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */
                                        echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */
                                        echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */
                                            echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </li>
            </ol>
        </div>
    </div>

    <?php if (!$block->getIsPreview() && !$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }

        </script>
    <?php endif; ?>
<?php endif; ?>

