<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$uniqueIdentifier = uniqid();
$catalogSearchHelper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<form id="search_mini_form_<?= /* @noEscape */ $uniqueIdentifier; ?>"
      class="pagebuilder-search-form pagebuilder-full-width <?= /* @noEscape */ $block->getData('classes') ?>"
      style="<?= /* @noEscape */ $block->getData('styles') ?>"
      action="<?= /* @noEscape */ $catalogSearchHelper->getResultUrl() ?>"
      method="get">
    <div class="form-search">
        <label for="search_<?= /* @noEscape */ $uniqueIdentifier; ?>"><?= $block->escapeHtml(__('Search:')) ?></label>
        <input id="search_<?= /* @noEscape */ $uniqueIdentifier; ?>" type="search"
               name="<?= $block->escapeHtml($catalogSearchHelper->getQueryParamName()) ?>"
               value="<?= $block->escapeHtml($catalogSearchHelper->getEscapedQueryText()) ?>" class="input-text"
               maxlength="<?= $block->escapeHtml($catalogSearchHelper->getMaxQueryLength()); ?>"
               placeholder="<?= $block->escapeHtml($block->getData('placeholder')); ?>"/>
        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Search')) ?>" class="button search-button">
            <?= $block->escapeHtmlAttr(__('Search')) ?>
        </button>
        <div id="search_autocomplete_<?= /* @noEscape */ $uniqueIdentifier; ?>" class="search-autocomplete"></div>
    </div>
</form>
