<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Single Product Block Template
 * @var $this Gene_BlueFoot_Block_Entity_Pagebuilder_Block_Catalog_Single
 *
 */
?>
<div class="gene-bluefoot-product gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <img src="{{ product_id.image }}" class="gene-bluefoot-product-image"/>
    <h3 class="gene-bluefoot-product-name">{{ product_id.name }}</h3>
    <p class="gene-bluefoot-product-sku">{{ product_id.sku }}</p>
    <p class="gene-bluefoot-product-price">{{ product_id.price }}</p>
</div>