<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\PageBuilder\Block\Adminhtml\Stage\Render $block */
?>
<script type="text/javascript">
    <?php
    // Shim localStorage without detection as it will not work as the iframe is sandboxed.
    ?>
    Object.defineProperty(
        window,
        'localStorage',
        {
            get: function () {
                return {
                    _data: {},
                    setItem: function (id, val) {
                        return this._data[id] = String(val);
                    },
                    getItem: function (id) {
                        return this._data.hasOwnProperty(id) ? this._data[id] : undefined;
                    },
                    removeItem: function (id) {
                        return delete this._data[id];
                    },

                    clear: function () {
                        return this._data = {};
                    }
                };
            }
        }
    );
</script>
<script type="text/javascript" src="<?= $block->escapeUrl($block->getRequireJsUrl()); ?>"></script>
<script type="text/javascript" src="<?= $block->escapeUrl($block->getRequireJsConfigUrl()); ?>"></script>
<script type="text/javascript">
    <?php
    // Override the text! RequireJS plugin to allow us to load templates from the parent window
    ?>
    require.config({
        'map': {
            '*': {
                'text': 'Magento_PageBuilder/js/render/requirejs/text',
            }
        },
    });

    <?php
    /**
     * To be able to override the text plugin we need the Magento template engine to be used, as the template engine
     * within lib has a dependency on the text! plugin we need to ensure we set the template engine before the
     * dependency blocks us.
     */
    ?>
    require([
        'ko',
        'Magento_Ui/js/lib/knockout/template/engine',
    ], function (ko, templateEngine) {
        'use strict';

        ko.uid = 0;
        ko.setTemplateEngine(templateEngine);
    });
</script>
<script type="text/javascript">
    require(['Magento_PageBuilder/js/render/frame'], function (listen) {
        listen();
    });
</script>
Page Builder Render Frame