<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\PageBuilder\Block\Adminhtml\Stage\Render $block */
?>
<script>
    <?php
    /**
     * Shim localStorage always within the iframe to ensure any calls from Magento API's do not fail due to same origin
     * policies.
     */
    ?>
    Object.defineProperty(
        window,
        'localStorage',
        {
            get: function () {
                return {
                    _data: {},
                    setItem: function (id, val) {
                        return this._data[id] = String(val);
                    },
                    getItem: function (id) {
                        return this._data.hasOwnProperty(id) ? this._data[id] : undefined;
                    },
                    removeItem: function (id) {
                        return delete this._data[id];
                    },

                    clear: function () {
                        return this._data = {};
                    }
                };
            }
        }
    );
</script>
<script src="<?= $block->escapeUrl($block->getRequireJsUrl()); ?>"></script>
<script src="<?= $block->escapeUrl($block->getRequireJsConfigUrl()); ?>"></script>
<script>
    <?php
    /**
     * Override the text! plugin within the iframe to ensure we can pipe any XHR requests through to the parent window
     * as the same origin policy will not allow us to load the templates within this iframe.
     */
    ?>
    require.config({
        'map': {
            '*': {
                'text': 'Magento_PageBuilder/js/render/requirejs/text',
            }
        },
    });

    <?php
    /**
     * To be able to override the text plugin we need the Magento template engine to be used, as the template engine
     * within lib has a dependency on the text! plugin we need to ensure we set the template engine before the
     * dependency blocks us.
     */
    ?>
    require([
        'ko',
        'Magento_Ui/js/lib/knockout/template/engine',
    ], function (ko, templateEngine) {
        'use strict';

        ko.uid = 0;
        ko.setTemplateEngine(templateEngine);
    });
</script>
<script>
    require(['Magento_PageBuilder/js/render/frame'], function (listen) {
        listen(<?= /* @noEscape */ $block->getPageBuilderConfig(); ?>);
    });
</script>
<div>Page Builder Render Frame</div>