<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\PageBuilder\Block\Adminhtml\Html\Head\BabelPolyfill */

if ($block->shouldLoadPolyfill()): ?>
<script type="text/javascript">
    if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
        document.write('<script src="<?= $block->getJsUrl() ?>"><\/script>');
    }
</script>
<?php endif; ?>

