<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Buttons Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
?>

<?php if ($block->hasChildEntities('button_items')) : ?>

    <?php $_collection = $block->getChildEntities('button_items'); ?>
    <div class="bluefoot-buttons <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <?php foreach ($_collection as $_block) : ?>
            <?php echo $_block->toHtml(); ?>
        <?php endforeach; ?>
    </div>

<?php endif; ?>