<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Button Item Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_action = "location.href='" . $_entity->getLinkUrl() . "'";
?>
<button type="button" onclick="<?php echo $_action; ?>"
        class="bluefoot-button button <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <span><span><?php echo $_entity->getLinkText(); ?></span></span>
</button>