<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Button Item Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_action = "location.href='" . $_entity->getLinkUrl() . "'";
?>
<button type="button" onclick="<?php echo $_action; ?>"
        class="bluefoot-button button <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <span><span><?php echo $_entity->getLinkText(); ?></span></span>
</button>