<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Static Block Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_block = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($_entity->getBlockId())->toHtml();
?>
<?php
// Check if the block is active on the current store
if ($_block != '') : ?>
    <div
        class="bluefoot-static-block <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
        <?php echo $_block; ?>
    </div>
<?php endif; ?>
