<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 *
 * Textarea Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
?>
<div
    class="bluefoot-entity bluefoot-textarea <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <?php echo $_entity->getTextarea(); ?>
</div>