<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Carousel Slider Item Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $this->getEntity();
$_count = $this->getCount();
$_urlPrefix = $this->getUrl('pub/media/gene-cms');
$_classes = 'slide-' . $_count;
// Hide all but the first slide
if ($_count > 1):
    $_classes .= ' hidden-on-load';
endif;

$this->setCssClasses($_classes);
?>
<div class="bluefoot-slide <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <?php if ($_entity->getLinkUrl()): ?>
        <a href="<?php echo $_entity->getLinkUrl(); ?>" class="bluefoot-slide-content"<?php echo ($_entity->getTargetBlank()) ? ' target="_blank"':'' ; ?>>
    <?php else: ?>
        <span class="bluefoot-slide-content">
    <?php endif ;?>

    <?php if ($_entity->getMobileImage()): ?>
        <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-hidden"/>
        <img src="<?php echo $_urlPrefix . $_entity->getMobileImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" class="bluefoot-mobile-only"/>
    <?php else: ?>
        <img src="<?php echo $_urlPrefix . $_entity->getImage(); ?>"  alt="<?php echo $_entity->getAltTag(); ?>" title="<?php echo $_entity->getTitleTag(); ?>" />
    <?php endif; ?>

    <?php if ($_entity->getLinkUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif ;?>
</div>