<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Carousel Template - this carousel uses the jQuery plugin Slick <http://kenwheeler.github.io/slick/>
 * Thanks to Ken Wheeler for allowing us to distribute his plugin with the Gene CMS
 *
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
$_entity = $this->getEntity();

if ($_entity->getShowDots()):
    $this->setCssClasses('bluefoot-slider-with-dots');
endif;

?>
<?php if ($this->hasChildEntities('slider_items')): ?>

    <?php $_collection = $this->getChildEntities('slider_items'); ?>
    <div id="bluefoot-slider-<?php echo $this->getEntity()->getId(); ?>" class="bluefoot-slider bluefoot-full-width <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <?php foreach ($_collection as $_block): ?>
            <?php echo $_block->toHtml(); ?>
        <?php endforeach; ?>
    </div>

    <script type="text/javascript">
        require(['jquery','slick'], function(jQuery){
            jQuery(function() {
                /* [Slick JS] */
                jQuery('#bluefoot-slider-<?php echo $this->getEntity()->getId(); ?>').slick({
                    infinite: <?php echo ($_entity->getIsInfinite()) ? 'true' : 'false' ; ?>,
                    dots: <?php echo ($_entity->getShowDots()) ? 'true' : 'false' ; ?>,
                    slidesToShow: <?php echo ($_entity->getSlidesToShow()) ? $_entity->getSlidesToShow() : 1 ; ?>,
                    slidesToScroll: <?php echo ($_entity->getSlidesToScroll()) ? $_entity->getSlidesToScroll() : 1 ; ?>,
                    arrows: <?php echo ($_entity->getShowArrows()) ? 'true' : 'false' ; ?>,
                    autoplay: <?php echo ($_entity->getAutoplay()) ? 'true' : 'false' ; ?>,
                    autoplaySpeed: <?php echo ($_entity->getAutoplayPlaySpeed()) ? $_entity->getAutoplayPlaySpeed() : '5000' ; ?>,
                    fade: <?php echo ($_entity->getFade()) ? 'true' : 'false' ; ?>,
                    prevArrow:'<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
                    nextArrow:'<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
                    <?php echo ($_entity->getSliderAdditionalSettings()) ? ',' . $_entity->getSliderAdditionalSettings()  : '' ; ?>
                });
            });
        });
    </script>

<?php endif; ?>

<div class="slider-test">
    <img src="http://magento2.vagrant158/pub/media/gene-cms//w/a/wave-3_2.jpg" />
    <img src="http://magento2.vagrant158/pub/media/gene-cms//w/a/wave-3_2.jpg" />
    <img src="http://magento2.vagrant158/pub/media/gene-cms//w/a/wave-3_2.jpg" />
    <img src="http://magento2.vagrant158/pub/media/gene-cms//w/a/wave-3_2.jpg" />
</div>

<script type="text/javascript">
    require(['jquery','slick'], function(jQuery){
        jQuery(function() {
            /* [Slick JS] */
            jQuery('.slider-test').slick({
                slidesToShow:1
            });
        });
    });
</script>
