<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Chloe Langford <chloe@gene.co.uk>
 *
 * Map Block Template
 * @var $this @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\Video
 *
 */
$_entity = $this->getEntity();
$_video = $this->getVideoData();
$_styles = '';
if ($_entity->getVideoHeight()): $_styles .= 'height:' . $_entity->getVideoHeight() . ';'; endif;
if ($_entity->getVideoWidth()): $_styles .= 'width:' . $_entity->getVideoWidth() . ';'; endif;

if($_video): ?>
    <div id="bluefoot-video-<?php echo $_entity->getEntityId(); ?>" class="bluefoot-video  <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <iframe src="<?php echo $_video->getUrl() ?>"<?php echo ($_entity->getVideoHeight()) ? ' height="' . $_entity->getVideoHeight() . '"': '' ; ?><?php echo ($_entity->getVideoWidth()) ? ' width="' . $_entity->getVideoWidth() . '"': '' ; ?> style="<?php echo $_styles; ?>" frameborder="0"></iframe>
    </div>
<?php endif; ?>