<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PageBuilder\Block\Adminhtml\System\Config\EnableButton $block
 */

?>
<script type="text/x-magento-init">
    {
        "<?= $block->getEnablePageBuilderSelector() ?>": {
            "Magento_PageBuilder/js/system/config/enableButton": {
                "modalTitleText": <?= /* @noEscape */ json_encode($block->getModalTitleText()) ?>,
                "modalContentBody": <?= /* @noEscape */ json_encode($block->getModalContentBody()) ?>
            }
        }
    }
</script>
