<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PageBuilder\Block\Adminhtml\System\Config\Form\Field\GoogleMapsApiKey $block
 */
?>
<button class="scalable"
        type="button"
        id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
        data-mage-init='{
            "Magento_PageBuilder/js/system/config/google-maps-api-key-validator": {
                "elementId": "<?= $block->escapeJs($block->getHtmlId()) ?>",
                "validateUrl": "<?= $block->escapeJs($block->getValidateUrl()) ?>",
                "buttonLabel": "<?= $block->escapeJs($block->getButtonLabel()) ?>",
                "validLabel": "<?= $block->escapeJs($block->getValidLabel()) ?>",
                "invalidLabel": "<?= $block->escapeJs($block->getInvalidLabel()) ?>",
                "sourceField": "<?= $block->escapeJs($block->getSourceField()) ?>"
            }
        }'
        disabled="disabled"
><span class="result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span></button>
