<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PageBuilder\Block\Adminhtml\System\Config\GoogleMapsApiValidator $block
 */
?>
<button class="scalable" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>" data-mage-init='{
    "Magento_PageBuilder/js/system/config/google-maps-api-validator": {
        "elementId": "<?= $block->escapeJs($block->getHtmlId()) ?>",
        "validationEndpoint": "<?= $block->escapeJs($block->getValidationEndpoint()) ?>",
        "validLabel": "<?= $block->escapeJs($block->getValidLabel()) ?>",
        "invalidLabel": "<?= $block->escapeJs($block->getInvalidLabel()) ?>",
        "sourceField": "<?= $block->escapeJs($block->getSourceField()) ?>"
    }
}'><span class="result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span></button>
