<?php
/**
 * Copyright 2018 Adobe
 * All Rights Reserved.
 */

/**
 * @var \Magento\PageBuilder\Block\Adminhtml\System\Config\Form\Field\GoogleMapsApiKey $block
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<button class="scalable"
        type="button"
        id="<?= $escaper->escapeHtmlAttr($block->getHtmlId()) ?>"
        data-mage-init='{
            "Magento_PageBuilder/js/system/config/google-maps-api-key-validator": {
                "elementId": "<?= $escaper->escapeJs($block->getHtmlId()) ?>",
                "validateUrl": "<?= $escaper->escapeJs($block->getValidateUrl()) ?>",
                "buttonLabel": "<?= $escaper->escapeJs($block->getButtonLabel()) ?>",
                "validLabel": "<?= $escaper->escapeJs($block->getValidLabel()) ?>",
                "invalidLabel": "<?= $escaper->escapeJs($block->getInvalidLabel()) ?>",
                "sourceField": "<?= $escaper->escapeJs($block->getSourceField()) ?>"
            }
        }'
        disabled="disabled"
><span class="result"><?= $escaper->escapeHtml($block->getButtonLabel()) ?></span></button>
