<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Column Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Column
 *
 */
$this->setCssClasses('bluefoot-column-' . $this->getColumnsFromWidth());
?>
<div class="bluefoot-column <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <?php echo $this->getRenderedChildHtml(); ?>
</div>