<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Column Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Column
 *
 */
$block->setCssClasses('bluefoot-column-' . $block->getColumnsFromWidth());
?>
<div class="bluefoot-column <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getAttributeHtml(); ?>>
    <?php echo $block->getChildHtml(); ?>
</div>