<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Column Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Column
 *
 */
?>
<div class="bluefoot-column bluefoot-column-<?php echo $this->getColumnsFromWidth(); ?> <?php echo $this->getFormData('css_classes'); ?><?php echo ($this->getFormData('remove_padding')) ? ' bluefoot-no-padding' : '' ; ?>">
    <?php echo $this->getRenderedChildHtml(); ?>
</div>