<?php
/**
 * Row default Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Row
 */
if ($block->getBackgroundStyles()) :
    $block->setCssClasses('with-media-background');
endif;
?>
<div class="bluefoot-row <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getAttributeHtml(); ?>>
    <div class="bluefoot-wrapper">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>