<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Row default Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Structural\Row
 *
 */
if ($block->getBackgroundStyles()) :
    $block->setCssClasses('with-media-background');
endif;
?>

<div class="bluefoot-row <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
    <div class="bluefoot-wrapper">
        <?php echo $block->getRenderedChildHtml(); ?>
    </div>
</div>