<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Buttons Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
?>
<div class="bluefoot-buttons-block gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    {{#child_blocks.button_items}}
        {{{html}}}
    {{/child_blocks.button_items}}
</div>