<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * HTML Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 */
?>
<div class="gene-bluefoot-html gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <div class="gene-bluefoot-html-code">
        {{{ html }}}
    </div>
</div>