<?php
/**
 * Copyright 2018 Adobe
 * All Rights Reserved.
 */

/** @var $escaper \Magento\Framework\Escaper */
?>
<div class="pagebuilder-modal-content-body">
    <p><?= $escaper->escapeHtml(__('This will change your Admin and storefront by:')) ?></p>
    <ul>
        <li>
            <strong><?= $escaper->escapeHtml(__('Removing PageBuilder\'s advanced content tools')) ?></strong>
            <?= $escaper->escapeHtml(
                __('from their assigned text fields and adding a basic text editor as replacement.')
            ) ?>
        </li>
        <li>
            <strong><?= $escaper->escapeHtml(__('Potentially creating display errors on your storefront')) ?></strong>
            <?= $escaper->escapeHtml(
                __(', due to content reformatting. Also, some content may no longer be editable from within the Admin.')
            ) ?>
        </li>
    </ul>
</div>
