<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "bluefoot-panel": {
                            "component": "bluefoot/stage/panel",
                            "template": "Gene_BlueFoot/component/core/stage/panel.html",
                            "config": <?php echo $this->getConfig(); ?>
                        }
                    }
                }
            }
    }
</script>

<div data-bind="scope: 'bluefoot-panel'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<div data-bind="scope: 'bluefoot_edit.bluefoot_edit'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
