<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Advanced CMS row template
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $advancedCms \Gene\BlueFoot\Model\Stage\Save\Renderer\Block
 */
$advancedCms = $block->getAdvancedCms();
// @todo determine format of storing and rendering column width
?>
<div<?php echo $advancedCms->getAttributeHtml(['class' => ['bluefoot-column']]); ?>>
    <?php echo $advancedCms->getDataHtml(); ?>
    <?php echo $block->getChildHtml(); ?>
</div>