<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Generic block for content blocks without rendering blocks
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $advancedCms \Gene\BlueFoot\Model\Stage\Save\Renderer\Block
 */
$advancedCms = $block->getAdvancedCms();
?>
<div<?php echo $advancedCms->getAttributeHtml(); ?>>
    <?php echo $advancedCms->getDataHtml(); ?>
    <?php echo $block->getChildHtml(); ?>
</div>