<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Newsletter Signup Block Template
 * @var $this Gene_Cms_Block_Entity_Pagebuilder_Block_Newsletter
 *
 */
?>
<div class="gene-cms-newsletter-block">
    <h3>{{{ title }}}</h3>
    <span class="gene-cms-newsletter-block-label">{{{ label }}}</span>
    <span class="gene-cms-newsletter-block-input">{{{ placeholder }}}</span>
    <button type="button" class="gene-cms-block-button">{{{ button_text }}}</button>
</div>