<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Newsletter Signup Block Template
 * @var $this Gene_Cms_Block_Entity_Pagebuilder_Block_Default
 *
 */
?>
<div class="gene-cms-search-block">
    <span class="gene-cms-search-block-input">
        {{{ placeholder }}}
        <button type="button" class="gene-cms-block-button"><i class="fa fa-search"></i></button>
    </span>
</div>