<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Conor Farrell <conor@gene.co.uk>
 *
 * Slider Advanced Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
?>
<div id="gene-bluefoot-slider-{{entity_id}}" class="bluefoot-advanced-slider gene-bluefoot-slider bluefoot-entity-align-{{ align }}">
    {{#child_blocks.advanced_slider_items}}
    {{{html}}}
    {{/child_blocks.advanced_slider_items}}
</div>


<script type="text/javascript">
    jQuery(function() {

        /* [Slick JS] */
        var arrows = false;
        if ('{{show_arrows}}' == 'Yes'){ arrows = true }

        var dots = false;
        if ('{{show_dots}}' == 'Yes'){ dots = true }

        var autoplay = false;
        if ('{{autoplay}}' == 'Yes'){ autoplay = true }

        var fade = false;
        if ('{{fade}}' == 'Yes'){ fade = true }


        jQuery('#gene-bluefoot-slider-{{entity_id}}').on('init', function(event, slick){
            jQuery('.slick-dots button, .slick-arrow').addClass('no-edit');
        });

        jQuery('#gene-bluefoot-slider-{{entity_id}}').slick({
            dots:dots,
            slidesToShow:1,
            slidesToScroll:1,
            arrows: arrows,
            autoplay: autoplay,
            fade: fade,
            infinite: false,
            prevArrow:'<button type="button" class="slick-prev button"><span><span>&lt;</span></span></button>',
            nextArrow:'<button type="button" class="slick-next button"><span><span>&gt;</span></span></button>'
        });


    });
</script>