<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Driver Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\Abstract
 *
 */
?>
<div class="gene-bluefoot-driver gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">
    <img src="/media/gene-cms/{{ image }}" />
    <span class="gene-bluefoot-driver-title">{{ link_text }}</span>
</div>