<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Slider Block Template
 * @var $this Gene_Cms_Block_Entity_Pagebuilder_Block_Default
 *
 */
?>
<div id="gene-cms-slider-{{entity_id}}" class="gene-cms-slider">
    {{#child_blocks.slider_items}}
    {{{html}}}
    {{/child_blocks.slider_items}}
</div>


<script type="text/javascript">
    jQuery(function() {

        /* [Slick JS] */

        // Set default values @todo - find a way to make this work with translations

        var arrows = false;
        if ('{{show_arrows}}' == 'Yes'){ arrows = true }

        var dots = false;
        if ('{{show_dots}}' == 'Yes'){ dots = true }

        var autoplay = false;
        if ('{{autoplay}}' == 'Yes'){ autoplay = true }

        var fade = false;
        if ('{{fade}}' == 'Yes'){ fade = true }

        var slidesToShow = '{{slides_to_show}}';
        if (slidesToShow == '' || fade){ slidesToShow = 1 }

        var slidesToScroll = '{{slides_to_scroll}}';
        if (slidesToScroll == '' || fade){ slidesToScroll = 1 }



        jQuery('#gene-cms-slider-{{entity_id}}').on('init', function(event, slick){

            jQuery('.slick-dots button, .slick-arrow').addClass('no-edit');

        });

        jQuery('#gene-cms-slider-{{entity_id}}').slick({
            dots:dots,
            slidesToShow:parseInt(slidesToShow),
            slidesToScroll:parseInt(slidesToScroll),
            arrows: arrows,
            autoplay: autoplay,
            fade: fade,
            infinite: false
        });


    });
</script>