<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Chloe Langford <chloe@gene.co.uk>
 *
 * Video Block Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\Abstract
 *
 */
?>
<div id="gene-bluefoot-video-{{ entity_id }}" class="gene-bluefoot-video-block gene-bluefoot-pagebuilder-block clearfix bluefoot-entity-align-{{ align }}">

    {{#video_url.url}}
      <div class="gene-bluefoot-video-container">
        <iframe src="{{ video_url.url }}" width="{{ video_width }}" height="{{ video_height }}" style="width:{{ video_width }};height:{{ video_height }};"></iframe>
      </div>
    {{/video_url.url}}
    {{^video_url.url}}
      <p><i class="fa fa-play"></i> Video (not found)</p>
    {{/video_url.url}}

</div>