<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Button Item Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $this->getEntity();
$_action = "location.href='" . $_entity->getLinkUrl() . "'";
?>
<button type="button" onclick="<?php echo $_action; ?>" class="bluefoot-button button <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
    <span><span><?php echo $_entity->getLinkText(); ?></span></span>
</button>