<?php
/**
 * Advanced CMS heading template
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var $advancedCms \Gene\BlueFoot\Model\Stage\Save\Renderer\Block
 */
$advancedCms = $block->getAdvancedCms();
$headingType = 'h2'; /* @todo change how this is stored */
?>
<<?php echo $headingType; ?><?php echo $advancedCms->getAttributeHtml(['class' => ['bluefoot-entity']]); ?>>
    <?php echo $advancedCms->getDataHtml(); ?>
    <span><?php echo $block->escapeHtml($advancedCms->getEntityData('title')); ?></span>
</<?php echo $headingType; ?>>