<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Heading Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\AbstractBlock
 *
 */
//$headingType = strtolower($block->getEntityData('heading_type'));
$headingType = 'h2'; // @todo determine how we're storing content block fields to convert the entity data to values
?>
<<?php echo $headingType; ?> class="bluefoot-entity <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getAttributeHtml(); ?>>
    <span><?php echo $block->escapeHtml($block->getEntityData('title')); ?></span>
</<?php echo $headingType; ?>>