<?php
/**
 * BlueFoot
 *
 * Version 1.0
 *
 * @author Hob Adams <hob@gene.co.uk>
 *
 * Heading Template
 * @var $block \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $block->getEntity();
$_headingType = strtolower($block->getAttributeText('heading_type'));
?>
<<?php echo $_headingType; ?> class="bluefoot-entity <?php echo $block->getCssAttributes(); ?>"<?php echo $block->getStyleAttributes(); ?>>
<span><?php echo $block->escapeHtml($_entity->getTitle()); ?></span></<?php echo $_headingType; ?>>