<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Chloe Langford <chloe@gene.co.uk>
 *
 * Facebook Feed Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $this->getEntity();

if($_entity->getFacebookUrl()): ?>
    <div id="fb-root"></div>

    <div class="bluefoot-facebook-feed <?php echo $this->getCssAttributes(); ?>"<?php echo $this->getStyleAttributes(); ?>>
        <div class="fb-page" data-href="<?php echo $_entity->getFacebookUrl(); ?>" <?php echo $_entity->getFacebookTabs() ? ' data-tabs="' . $_entity->getFacebookTabs() . '"' : ''; ?><?php echo ($_entity->getFacebookFeedWidth()) ? ' data-width="' . $_entity->getFacebookFeedWidth() . '"': '' ?><?php echo ($_entity->getFacebookFeedHeight()) ? ' data-height="' . $_entity->getFacebookFeedHeight() . '"': '' ?><?php echo (!$_entity->getFacebookCoverPhoto()) ? ' data-small-header="true"' : '' ?> data-adapt-container-width="true" data-show-facepile="true">

            <div class="fb-xfbml-parse-ignore">
                <blockquote cite="<?php echo $_entity->getFacebookUrl(); ?>">
                    <a href="<?php echo $_entity->getFacebookUrl(); ?>"><?php $_entity->getFacebookPage() ?></a>
                </blockquote>
            </div>
        </div>
    </div>

    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

<?php endif; ?>