<?php
/**
 * BlueFoot
 *
 * Version 1.0
 * @author Chloe Langford <chloe@gene.co.uk>
 *
 * Twitter Feed Template
 * @var $this \Gene\BlueFoot\Block\Entity\PageBuilder\Block\AbstractBlock
 *
 */
$_entity = $this->getEntity();
$_size = strtolower($this->getAttributeText('pin_size'));

if($_entity->getPinBoardId()): ?>

    <script async defer src="//assets.pinterest.com/js/pinit.js"></script>

    <a data-pin-do="embedBoard" data-pin-board-width="130" data-pin-scale-height="659" data-pin-scale-width="115" href="https://www.pinterest.com/MakeupUtopia/inspiring-hair/"></a>


<?php endif; ?>